services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper
    hostname: zookeeper-server
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    hostname: kafka-broker
    restart: always
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      zookeeper:
        condition: service_started
    healthcheck:
      test: ['CMD', 'nc', '-z', 'kafka-broker', '9093']
      interval: 2s
      timeout: 1s
      retries: 15
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker:9093

  kafka-init:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka-init
    init: true
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
    volumes:
    - ./local/kafka/entrypoint/kafka-entrypoint.sh:/usr/bin/kafka-entrypoint.sh
    command: [ '/bin/bash', '-c', '/usr/bin/kafka-entrypoint.sh']

  redpanda-console:
    image: redpandadata/console:v2.7.2
    container_name: redpanda-console
    hostname: redpanda-console
    restart: always
    ports:
      - 9090:8080
    depends_on:
      kafka:
        condition: service_started
    environment:
      KAFKA_BROKERS: kafka-broker:9093